#pragma once

#include <pebble.h>

#include "helper.h"

enum {
  WATCHFACE_ICON_GRID_WIDTH = 28,
  WATCHFACE_ICON_GRID_HEIGHT = 28,
  WATCHFACE_ICON_CENTER_X = 14,
  WATCHFACE_ICON_CENTER_Y = 14,
};

// Blueprints
// Reference Design
enum {
  DESIGN_FACE_WIDTH = 200,
  DESIGN_FACE_HEIGHT = 228,
  DESIGN_X_MARGIN = 4,
  DESIGN_Y_MARGIN = 10,
  DESIGN_ICON_TEXT_GAP = 1,
  DESIGN_TIME_Y_PERCENT = 20,
  DESIGN_BATTERY_BAR_WIDTH_PERCENT = 75,
  DESIGN_BATTERY_BAND_HEIGHT = 16,
  DESIGN_BATTERY_TRACK_HEIGHT = 6,
  DESIGN_BATTERY_FILL_HEIGHT = 4,
  DESIGN_BATTERY_BOLT_WIDTH = 18,
  DESIGN_BATTERY_BOLT_HEIGHT = 18,
  DESIGN_STEPS_PROGRESS_HEIGHT = 4,
};

// Full blueprint
enum {
  DESIGN_FULL_X_MARGIN = DESIGN_X_MARGIN,
  DESIGN_FULL_Y_MARGIN = DESIGN_Y_MARGIN,
  DESIGN_FULL_ICON_WIDTH = WATCHFACE_ICON_GRID_WIDTH,
  DESIGN_FULL_ICON_HEIGHT = WATCHFACE_ICON_GRID_HEIGHT,
  DESIGN_FULL_DATE_TEXT_HEIGHT = 28,
#if defined(PBL_PLATFORM_GABBRO)
  DESIGN_FULL_TIME_TEXT_HEIGHT = 72,
#else
  DESIGN_FULL_TIME_TEXT_HEIGHT = 60,
#endif
  DESIGN_FULL_DATA_TEXT_HEIGHT = 28,
  DESIGN_FULL_LOCATION_TEXT_HEIGHT = 19,
#ifdef PBL_HEALTH
  DESIGN_FULL_STEPS_TEXT_WIDTH = 56,
  DESIGN_FULL_BPM_TEXT_WIDTH = 36,
#endif
};

// Compact blueprint
enum {
  DESIGN_COMPACT_X_MARGIN = DESIGN_X_MARGIN >> 1,
  DESIGN_COMPACT_Y_MARGIN = PBL_IF_ROUND_ELSE(DESIGN_Y_MARGIN,
      HELPER_CLAMP_MIN((DESIGN_Y_MARGIN >> 1), DESIGN_STEPS_PROGRESS_HEIGHT + 2)),
  DESIGN_COMPACT_TIME_Y_PERCENT = 24,
  DESIGN_COMPACT_ICON_TEXT_GAP = 1,
  DESIGN_COMPACT_ICON_WIDTH = 18,
  DESIGN_COMPACT_ICON_HEIGHT = 18,
  DESIGN_COMPACT_DATE_TEXT_HEIGHT = 18,
  DESIGN_COMPACT_TIME_TEXT_HEIGHT = 42,
  DESIGN_COMPACT_DATA_TEXT_HEIGHT = 18,
  DESIGN_COMPACT_LOCATION_TEXT_HEIGHT = 17,
#ifdef PBL_HEALTH
  DESIGN_COMPACT_STEPS_TEXT_WIDTH = 42,
  DESIGN_COMPACT_BPM_TEXT_WIDTH = 30,
#endif
};

typedef struct {
  GRect track;
  GRect fill;
  GRect bolt;
} LayoutBatteryStratum;

typedef struct {
  GRect icon;
  GRect text;
} LayoutMetricWithIcon;

typedef struct {
  LayoutMetricWithIcon steps;
  GRect progress;
} LayoutMetricPairWithProgress;

typedef struct {
  GRect time;
  GRect date;
  LayoutBatteryStratum battery;
  LayoutMetricWithIcon climate;
  GRect location;
#ifdef PBL_HEALTH
  LayoutMetricPairWithProgress steps_layer;
  LayoutMetricWithIcon bpm;
#endif
} CalculatedLayout;
