#pragma once

#include <pebble.h>

#if (defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO))
#define IS_LARGE_DISPLAY 1
#else
#define IS_LARGE_DISPLAY 0
#endif

#define FULL_OR_COMPACT(a, b) ((IS_LARGE_DISPLAY) ? (a) : (b))

// Reference design icon dimensions
enum {
  WATCHFACE_ICON_GRID_WIDTH = 28,
  WATCHFACE_ICON_GRID_HEIGHT = 28,
  WATCHFACE_ICON_CENTER_X = WATCHFACE_ICON_GRID_WIDTH >> 1,
  WATCHFACE_ICON_CENTER_Y = WATCHFACE_ICON_GRID_HEIGHT >> 1,
};

// Layout placement based on full or compact characterization
enum {
  X_MARGIN = 6,
  Y_MARGIN = 6,
  TIME_Y_PERCENT = 20,
#if defined(PBL_PLATFORM_GABBRO)
  TIME_TEXT_HEIGHT = 72,
#else
  TIME_TEXT_HEIGHT = FULL_OR_COMPACT(60, 42),
#endif
  HORIZ_RULE_SIZE_PERCENT = 45,
  HORIZ_RULE_HEIGHT = FULL_OR_COMPACT(4, 3),
  BATTERY_BAR_SIZE_PERCENT = 72,
  BATTERY_BAND_HEIGHT = FULL_OR_COMPACT(20, 16),
  BATTERY_TRACK_HEIGHT = FULL_OR_COMPACT(10, 8),
  BATTERY_FILL_HEIGHT = FULL_OR_COMPACT(6, 4),
  BATTERY_TRACK_FILL_DIFF = BATTERY_TRACK_HEIGHT - BATTERY_FILL_HEIGHT,
  BATTERY_TRACK_FILL_OFFSET = BATTERY_TRACK_FILL_DIFF >> 1,
  BATTERY_BOLT_HEIGHT = BATTERY_BAND_HEIGHT,
  BATTERY_BOLT_WIDTH = BATTERY_BOLT_HEIGHT,
  BT_ICON_WIDTH = BATTERY_BOLT_WIDTH,
  BT_ICON_HEIGHT = BATTERY_BOLT_HEIGHT,
  TEMP_X_PERCENT = 35,
  ICON_TEXT_GAP = 2,
  ICON_WIDTH = FULL_OR_COMPACT(28, 18),
  ICON_HEIGHT = ICON_WIDTH,
  DATE_TEXT_HEIGHT = ICON_HEIGHT,
  DATA_TEXT_HEIGHT = DATE_TEXT_HEIGHT,
  LOCATION_TEXT_WIDTH_PERCENT = 72,
  LOCATION_TEXT_HEIGHT = FULL_OR_COMPACT(18, 16),
#ifdef PBL_HEALTH
  STEPS_TEXT_WIDTH = FULL_OR_COMPACT(56, 42),
  STEPS_PROGRESS_HEIGHT = 4,
  BPM_TEXT_WIDTH = STEPS_TEXT_WIDTH,
#endif
};
