#pragma once

#include <pebble.h>

#include "helper.h"

enum {
  TEMP_UNIT_F = 0,
  TEMP_UNIT_C,
  TEMP_UNIT_MIN = TEMP_UNIT_F,
  TEMP_UNIT_MAX = TEMP_UNIT_C,
  TEMP_UNIT_DEFAULT = TEMP_UNIT_F,
};

enum {
  TIME_FMT_24 = 0,
  TIME_FMT_12,
  TIME_FMT_MIN = TIME_FMT_24,
  TIME_FMT_MAX = TIME_FMT_12,
  TIME_FMT_DEFAULT = TIME_FMT_24,
};

typedef enum {
  DISPLAY_MODE_LIGHT_MONOCHROME = 0,
  DISPLAY_MODE_MIN = DISPLAY_MODE_LIGHT_MONOCHROME,
  DISPLAY_MODE_DEFAULT = DISPLAY_MODE_LIGHT_MONOCHROME,
  DISPLAY_MODE_DARK_MONOCHROME = 1,
#ifdef PBL_COLOR
  DISPLAY_MODE_LIGHT_COLOR = 2,
  DISPLAY_MODE_DARK_COLOR = 3,
  DISPLAY_MODE_MAX = DISPLAY_MODE_DARK_COLOR,
#else
  DISPLAY_MODE_MAX = DISPLAY_MODE_DARK_MONOCHROME,
#endif
  DISPLAY_MODE_COUNT = DISPLAY_MODE_MAX + 1,
} SupportedDisplayModes;

enum {
  HR_SAMPLE_MINUTES_10 = 10,
  HR_SAMPLE_MINUTES_15 = 15,
  HR_SAMPLE_MINUTES_30 = 30,
  HR_SAMPLE_MINUTES_60 = 60,
  HR_SAMPLE_MINUTES_120 = 120,
  HR_SAMPLE_MINUTES_DEFAULT = HR_SAMPLE_MINUTES_15,
  HR_SAMPLE_MINUTES_MIN = HR_SAMPLE_MINUTES_10,
  HR_SAMPLE_MINUTES_MAX = HR_SAMPLE_MINUTES_120,
};

typedef enum {
  WEATHER_UPDATE_MINUTES_15 = 15,
  WEATHER_UPDATE_MINUTES_30 = 30,
  WEATHER_UPDATE_MINUTES_45 = 45,
  WEATHER_UPDATE_MINUTES_60 = 60,
  WEATHER_UPDATE_MINUTES_MAX = WEATHER_UPDATE_MINUTES_60,
  WEATHER_UPDATE_MINUTES_DEFAULT = WEATHER_UPDATE_MINUTES_15,
  WEATHER_UPDATE_MINUTES_MIN = WEATHER_UPDATE_MINUTES_15,
} WeatherUpdateMinutes;

enum {
  STEPS_GOAL_MIN = 4000,
  STEPS_GOAL_DEFAULT = 10000,
  STEPS_GOAL_MAX = 32000,
};

#define TEMP_UNIT_VALID(value) (HELPER_VALUE_IN_RANGE((value), TEMP_UNIT_MIN, TEMP_UNIT_MAX))
#define TIME_FORMAT_VALID(value) (HELPER_VALUE_IN_RANGE((value), TIME_FMT_MIN, TIME_FMT_MAX))
#define DISPLAY_MODE_VALID(value) \
  (HELPER_VALUE_IN_RANGE((value), DISPLAY_MODE_MIN, DISPLAY_MODE_MAX))
#define HR_SAMPLE_MINUTES_VALID(value) \
  ((HELPER_VALUE_IN_RANGE((value), HR_SAMPLE_MINUTES_MIN, HR_SAMPLE_MINUTES_MAX)))
#define STEPS_GOAL_VALID(value) (HELPER_VALUE_IN_RANGE((value), STEPS_GOAL_MIN, STEPS_GOAL_MAX))
#define WEATHER_UPDATE_MINUTES_VALID(value) \
  (HELPER_VALUE_IN_RANGE((value), WEATHER_UPDATE_MINUTES_MIN, WEATHER_UPDATE_MINUTES_MAX))

typedef struct {
  // Add persisted fields at the bottom
  uint8_t temp_unit;
  uint8_t time_format;
  SupportedDisplayModes display_mode;
  uint8_t weather_update_minutes;
#ifdef PBL_HEALTH
  uint8_t hr_sample_minutes;
  uint16_t steps_goal;
#endif
} WatchfaceSettings;

void settings_load(WatchfaceSettings* settings);
bool settings_save(const WatchfaceSettings* settings);
