#pragma once

typedef enum {
  ATAGLANCE_USE_AND_PERSIST_SETTINGS = 1,
  ATAGLANCE_MAX_STR_LEN = 16,

  // Reference display used for all layout decisions and icon styling.
  ATAGLANCE_DESIGN_FACE_HEIGHT = 228,
  ATAGLANCE_DESIGN_FACE_WIDTH = 200,

  // Product layout decisions.
  ATAGLANCE_DESIGN_CONTENT_MARGIN = 4,
  ATAGLANCE_DESIGN_ICON_TEXT_GAP = 4,
  ATAGLANCE_DESIGN_ROW_GAP = 8,
  ATAGLANCE_DESIGN_COLUMN_GAP = 8,
  ATAGLANCE_DESIGN_ICON_HEIGHT = 28,
  ATAGLANCE_DESIGN_ICON_WIDTH = 28,
  ATAGLANCE_DESIGN_DATE_ROW_HEIGHT = 20,
  ATAGLANCE_DESIGN_TIME_ROW_HEIGHT = 48,
  ATAGLANCE_DESIGN_HEALTH_ROW_HEIGHT = 20,
  ATAGLANCE_DESIGN_BOTTOM_ROW_HEIGHT = 20,
  ATAGLANCE_DESIGN_DATA_FIELD_WIDTH = 40
} AtAGlanceProductChoices;
