#pragma once

#define DEBUG_ATAGLANCE 1

typedef enum {
  ATAGLANCE_USE_AND_PERSIST_SETTINGS = 1,
  ATAGLANCE_MAX_STR_LEN = 16,

  // Reference display used for all layout decisions and icon styling.
  ATAGLANCE_DESIGN_FACE_HEIGHT = 228,
  ATAGLANCE_DESIGN_FACE_WIDTH = 200,
  // Product layout decisions.
  ATAGLANCE_DESIGN_CONTENT_MARGIN = 4,
  ATAGLANCE_DESIGN_ICON_TEXT_GAP = 4,
  ATAGLANCE_DESIGN_ROW_GAP = 8,
  ATAGLANCE_DESIGN_ICON_HEIGHT = 28,
  ATAGLANCE_DESIGN_ICON_WIDTH = 28,
  ATAGLANCE_DESIGN_DATE_TEXT_HEIGHT = 28,
  ATAGLANCE_DESIGN_TIME_TEXT_HEIGHT = 60,
  ATAGLANCE_DESIGN_HEALTH_TEXT_HEIGHT = 20,
  ATAGLANCE_DESIGN_BOTTOM_TEXT_HEIGHT = 20,
  ATAGLANCE_DESIGN_DATA_FIELD_WIDTH = 40
} AtAGlanceProductChoices;

#define ATAGLANCE_FONT_KEY_DATE_COMPACT FONT_KEY_GOTHIC_14_BOLD
#define ATAGLANCE_FONT_KEY_TIME_COMPACT FONT_KEY_BITHAM_42_MEDIUM_NUMBERS
#define ATAGLANCE_FONT_KEY_BPM_COMPACT FONT_KEY_GOTHIC_14
#define ATAGLANCE_FONT_KEY_STEPS_COMPACT FONT_KEY_GOTHIC_14
#define ATAGLANCE_FONT_KEY_BATTERY_COMPACT FONT_KEY_GOTHIC_14_BOLD
#define ATAGLANCE_FONT_KEY_CLIMATE_COMPACT FONT_KEY_GOTHIC_14

#define ATAGLANCE_FONT_KEY_DATE_FULL FONT_KEY_GOTHIC_24_BOLD
#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define ATAGLANCE_FONT_KEY_TIME_FULL FONT_KEY_LECO_60_NUMBERS_AM_PM
#else
#define ATAGLANCE_FONT_KEY_TIME_FULL FONT_KEY_LECO_42_NUMBERS
#endif
#define ATAGLANCE_FONT_KEY_BPM_FULL FONT_KEY_GOTHIC_18
#define ATAGLANCE_FONT_KEY_STEPS_FULL FONT_KEY_GOTHIC_18
#define ATAGLANCE_FONT_KEY_BATTERY_FULL FONT_KEY_GOTHIC_18_BOLD
#define ATAGLANCE_FONT_KEY_CLIMATE_FULL FONT_KEY_GOTHIC_18
