# -*- mode: python; -*-

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')
    include_dir = ctx.path.abspath() + '/../../src'

    binaries = []
    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.env.CFLAGS += ['-idirafter', include_dir]
        ctx.env.INCLUDES += [ctx.env.BUILD_DIR + '/src']
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        app_sources = ctx.path.ant_glob('src/c/**/*.c') + [
            ctx.path.find_resource('../../src/modules/climate_glyphs.c'),
            ctx.path.find_resource('../../src/modules/substratum_renderer.c'),
            ctx.path.find_resource('../../src/modules/substratum_computations.c'),
        ]
        ctx.pbl_build(source=app_sources,
                      target=app_elf,
                      bin_type='app')
        binaries.append({'platform': platform, 'app_elf': app_elf})
    ctx.env = cached_env

    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries)
